package com.xbb.communication_gateway.model;

import com.xbb.communication_gateway.model.base.BaseDictItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DictItem extends BaseDictItem<DictItem> {
	public static final DictItem dao = new DictItem().dao();
}
