package com.xbb.communication_gateway.model;

import com.xbb.communication_gateway.model.base.BaseDictType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DictType extends BaseDictType<DictType> {
	public static final DictType dao = new DictType().dao();
}
