package com.xbb.communication_gateway.model;

import com.xbb.communication_gateway.model.base.BaseRegion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Region extends BaseRegion<Region> {
	public static final Region dao = new Region().dao();
}
