package com.xbb.communication_gateway.model;

import com.xbb.communication_gateway.model.base.BaseTbTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbTest extends BaseTbTest<TbTest> {
	public static final TbTest dao = new TbTest().dao();
}
