package com.xbb.communication_gateway.model;

import com.xbb.communication_gateway.model.base.BaseUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRole extends BaseUserRole<UserRole> {
	public static final UserRole dao = new UserRole().dao();
}
