package com.xbb.communication_gateway.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRegion<M extends BaseRegion<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setAreaName(java.lang.String areaName) {
		set("areaName", areaName);
		return (M)this;
	}

	public java.lang.String getAreaName() {
		return getStr("areaName");
	}

	public M setAreaType(java.lang.String areaType) {
		set("areaType", areaType);
		return (M)this;
	}

	public java.lang.String getAreaType() {
		return getStr("areaType");
	}

	public M setRemarkMessage(java.lang.String remarkMessage) {
		set("remarkMessage", remarkMessage);
		return (M)this;
	}

	public java.lang.String getRemarkMessage() {
		return getStr("remarkMessage");
	}

	public M setRankNum(java.lang.Integer rankNum) {
		set("rankNum", rankNum);
		return (M)this;
	}

	public java.lang.Integer getRankNum() {
		return getInt("rankNum");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setUpdataTime(java.util.Date updataTime) {
		set("updataTime", updataTime);
		return (M)this;
	}

	public java.util.Date getUpdataTime() {
		return get("updataTime");
	}

	public M setParentId(java.lang.String parentId) {
		set("parentId", parentId);
		return (M)this;
	}

	public java.lang.String getParentId() {
		return getStr("parentId");
	}

}
