package com.xbb.communication_gateway.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbTest<M extends BaseTbTest<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public M setTestName(java.lang.String testName) {
		set("test_name", testName);
		return (M)this;
	}

	public java.lang.String getTestName() {
		return getStr("test_name");
	}

	public M setTestUrl(java.lang.String testUrl) {
		set("test_url", testUrl);
		return (M)this;
	}

	public java.lang.String getTestUrl() {
		return getStr("test_url");
	}

	public M setTestText(java.lang.String testText) {
		set("test_text", testText);
		return (M)this;
	}

	public java.lang.String getTestText() {
		return getStr("test_text");
	}

}
